### ISSUE TITLE
Simplify header

### ISSUE THREAD

**Issue by jscharett** [US-CBP/ngx-cbp-theme#7]
Should  some of the component features of the header be abstracted out so that users can include only the ones necessary?  For instance, If I don't want the Feedback link, then I simply don't include it.  Some like the following?

```
<cbp-header>
    <cbp-apps-menu></cbp-apps-menu>
    <cbp-feedback-link></cbp-feedback-link>
    <cbp-user-menu></cbp-user-menu>
</cbp-header>
```
The header itself would only provide the branding and the toggle button.

**Comment by yogeshgadge** [comment]
@davezen1 wondering how much of the cbp-header is customizable ? I was under the impression that no customization was allowed in terms of what its on it since that directly affected the goal of unified look & feel as users switched between applications. I understand that in the interim we have some freedom as to how each of the items on header are implemented. For example can we provide a default functionality of opening a dialog and "please contact such and such via <some@email>" or just mailto: <some@email>.

**Comment by jscharett** [comment]
Weather all the pieces are required or not would be good to know.  I thought I had heard that things like preferences and feedback were 'optional', but maybe I misunderstood.  Regardless, it might be better to still abstract those into there own components that contain the services; similar to how they are now.  Then, you simply pull them in and drop them into the header.  This would provide a nice separation of concerns.  Currently, the header has some hard dependencies on the services for these.  It might prove better to decouple those.

**Comment by yogeshgadge** [comment]
Markup requirement for the end developer:-

```html
<cbp-header>
    <cbp-feedback-link></cbp-feedback-link>
</cbp-header>
```

Additionally refactor necessary templates from `cbp-header.component.html` into appropriate components - mainly the feedback module.

**Comment by yogeshgadge** [comment]
We have use case for external facing applications which do not have other parts. We will need to open up all other parts of CBP Headers as per @jscharett to be configurable instead of the current opinionated. 

```html5
<cbp-header>
    <cbp-apps-menu></cbp-apps-menu>
    <cbp-feedback-link></cbp-feedback-link>
    <cbp-user-menu></cbp-user-menu>
</cbp-header>
```

**Comment by walhow** [comment]
+100 on the original comment (jscharett commented on Sep 7, 2017)

**Comment by yogeshgadge** [comment]
PR #47 closes this.
