### ISSUE TITLE
Use <header> for cbp-header

### ISSUE THREAD

**Issue by jscharett** [US-CBP/ngx-cbp-theme#8]
Can cbp-header be changed from an `md-toolbar` to a simple `header` tag?  Seems like it would be more semantic as well as accessible to use the standard html5 tag.  Is md-toolbar providing some sort of functionality?

**Comment by yogeshgadge** [comment]
At this point md-toolbar is serving  little functionality given how much we have customized. It's worth revisiting removal of md-toolbar.

**Comment by yogeshgadge** [comment]
Tried to remove `md-toolbar` and it turns out md-toolbar` still provides following functionality for us:-

1. Component theme from Color Palette which lets us use color="primary" 

Refer to 
https://github.com/angular/material2/blob/master/src/lib/toolbar/toolbar.ts#L31

2. Accessibility 

One example:
https://github.com/angular/material2/blob/master/src/lib/toolbar/toolbar.ts#L42

This functionality is small and we can easily provide this functionality.

However it does force us to roll our own component in place of `md-toolbar` and maintain it.  
While we may call that component just `header` but that goes against our conventions of prefixing components with `cbp-` namespace which is recommended by angular team and the enforcement of the policy is embedded right inside `angular-cli`.  

I am thinking it is better to reuse `md-toolbar` and piggy back on its functionality ?

**Comment by jscharett** [comment]
Yeah, ran into this as well.  Not as simple as just swapping header for md-toolbar due to layout and styling.  You might be right about piggy backing.  Will investigate options.

**Comment by yogeshgadge** [comment]
PR #12 removes md-toolbar
